### ISSUE TITLE
folder src is full source code not mix

### ISSUE THREAD

**Issue by firmanJS** [ayocodingit/boilerplate-express-service#1]
the src folder should only contain source code not mixed with .dockerignore packagelock dll
![Screenshot from 2021-10-05 09-24-44](https://user-images.githubusercontent.com/5679509/135950680-f41655f3-1371-42ec-b939-022de8b967a1.png)

**Comment by ayocodingit** [comment]
> the src folder should only contain source code not mixed with .dockerignore packagelock dll ![Screenshot from 2021-10-05 09-24-44](https://user-images.githubusercontent.com/5679509/135950680-f41655f3-1371-42ec-b939-022de8b967a1.png)

oh i see, your right thank for insight
